version: "3"

services:
  app:
    build: .
    container_name: portfolioapi-app
    ports:
      - "3000:3000"
    command: yarn start:dev
    volumes: 
      - .:/home/node/app
    depends_on:
      - redis

  redis:
    image: 'bitnami/redis:latest'
    container_name: portfolioapi-redis
    environment: 
      - ALLOW_EMPTY_PASSWORD=yes
