name: tomazcx.com CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v1
      - name: Deploy para meu hosting
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{secrets.REMOTE_HOST}}
          REMOTE_USER: ${{secrets.REMOTE_USER}}
          REMOTE_PORT: ${{secrets.REMOTE_PORT}}
          TARGET: ${{secrets.REMOTE_TARGET}}
          USER_LOGIN: ${{secrets.USER_LOGIN}}
          USER_PASSWORD: ${{secrets.USER_PASSWORD}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          JWT_EXPIRES_IN: ${{secrets.JWT_EXPIRES_IN}}
          MONGO_USER: ${{secrets.MONGO_USER}}
          MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}
          MONGO_URL: ${{secrets.MONGO_URL}}
          SENDGRID_KEY: ${{secrets.SENDGRID_KEY}}
